### ISSUE TITLE
Creating ETs and then publishing events leads to leaked connections

### ISSUE THREAD

**Issue by v-stepanov** [dehora/nakadi-java#237]
When I use eventType creation - I start getting leaked connection errors
```
2017-09-05 13:36:04.894  WARN 73002 --- [ ConnectionPool] nakadi.shadow.okhttp3.OkHttpClient       : A connection to https://nakadi-staging.aruha-test.zalan.do/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
```

I create ET using eventTypeResource.create(eventType) and then I get a lot of errors like that when I publish. If I don't create ET and just use publishing - I don't have any errors.

The problem doesn't happen if I use two separate instances of NakadiClient for ET creation and for publishing of events.

**Comment by satybald** [comment]
I confirm that the warning also occurs when starting a new `StreamProcessor`.

**Comment by dehora** [comment]
>create ET using eventTypeResource.create(eventType) and then I get a lot of errors like that when I publish.

I can't replicate this. For example using the same client to create an event type and then send a set of events:

```java
  public static void main(String[] args) throws Exception {
    String name = "test-gh237-1";
    NakadiClient client = NakadiClient.newBuilder()
        .baseURI("https://localhost:8000")
        .certificatePath("classpath:certs")
        .tokenProvider(scope -> Optional.of("Bearer "+ token()))
        .build();

    createEventType(client, name); // calls eventTypes.create(eventType)
    sendEvents(client, name, 10000); // calls eventResource.send(name, once per 1 event)
  }
```

isn't complaining. I'll keep looking but can you describe your setup in more detail?

**Comment by dehora** [comment]
> I can't replicate this.

Ok, this is what might going on. Any method on the client that returns a `Response` object has to have that object closed by the application. The reason a plain Response object is returned is because Nakadi has a set of API calls that either don't return response data or conditionally return response data.  [Event type creation](https://github.com/zalando/nakadi/blob/master/docs/_data/nakadi-event-bus-api.yaml#L186-L200) and  [Event posting](https://github.com/zalando/nakadi/blob/master/docs/_data/nakadi-event-bus-api.yaml#L384-L407) both behave this way which is why they return Response. 

So in this case I think these might help. For event type creation, the call can be wrapped in a twr:

```java
   Response response = eventTypes.create(et100);
   try(ResponseBody body = response.responseBody()) {
     System.out.println("CREATE ==========================");
      System.out.println(response.statusCode() + " " + response.reason());
      System.out.println(response.headers());
    }
```

The same approach can be taken for event sending:

```java
     Response send = eventResource.send(name, Lists.newArrayList(event)); 
    System.out.println(send); 
    send.responseBody().close(); // this response might or might not have a body
```

If you prefer to avoid a twr or calling `close()` for events, the event resource has `sendBatch` methods that will close the underlying connection (because it can serialise the response to a `BatchItemResponseCollection` in advance).

```java
      final BatchItemResponseCollection batch =
          eventResource.sendBatch(name, Lists.newArrayList(event));
```

I'll look at adding some convenience methods to the client for this (eg close on the top level Response object), but for now, generally any call that returns a Response requires the app to call `close()` on the `Response.ResponseBody`.

(It might be possible to have the client understand and examine exact error codes to pre-close response in certain cases, but it's unlikely to be bulletproof and will result in tight coupling due to being very precise about response codes. As a general thing APIs that return entities consistently tend to be easier to deal with for client development but there's nothing wrong in what the Nakadi API does based on the guidelines it follows.)

**Comment by dehora** [comment]
added a close call on Response in 0.9.10, closing for now.
